name: Backend CI

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: backendNode
      - uses: actions/setup-node@v4
        working-directory: backendNode
        with:
          node-version: 20
          cache: 'npm'
      - name: Jest tets
        working-directory: backendNode
        run: npm test
